 ####################### this is  a place that I will solve Eulersiete problems#################
# https://projecteuler.net
# problem=1
mylist=[]
for i in range(1,1000):
    if (i % 5 ==0 or i % 3==0):
        mylist.append(i)
print(sum(mylist))


# problem 2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
fibi=[1,2]
evenFibi=[]
iteration=2
while max(fibi) <=4000000:

    fib=fibi[iteration -1] + fibi[iteration -2]
    fibi.append(fib)

    iteration +=1
for i in range(len(fibi)-1):

    if fibi[i]%2==0:
        evenFibi.append(fibi[i])
print( 'the sum of fibioancy is:{}'.format(sum(evenFibi)))

#The prime factors of 13195 are 5, 7, 13 and 29.

#What is the largest prime factor of the number 600851475143 ?


n=600851475143
result = []
for i in range(2,n):
    while n % i == 0:
        #print i,"|",n
        n = n/i
        result.append(i)

    if n == 1:
        break

if n > 1: result.append(n)
print (result)

print(max(result))





